version: '3.4'

services:
  django_backend:
    image: django_backend
    hostname: django_backend
    container_name: django_backend
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000

  local-db:
    image: postgres
    hostname: local-db
    container_name: local-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: virtual_library
    ports:
      - 5432:5432
    volumes:
      - ./.docker/postgres:/var/lib/postgresql/data
      - /tmp:/tmp